[package]
name = "vscode-kit"
version = "0.1.0"
edition = "2024"

[lib]
name = "vscode_kit"
path = "src/lib.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
